# Sample using multistore with two Ceph clusters (ceph-0 and ceph-1) and swift-0.
apiVersion: core.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack
spec:
  glance:
    template:
      customServiceConfig: |
        [DEFAULT]
        debug=True
        enabled_backends = ceph-0:rbd,ceph-1:rbd,swift-0:swift
        [glance_store]
        default_backend = ceph-1
        [ceph-0]
        rbd_store_ceph_conf = /etc/ceph/ceph-0.conf
        store_description = "RBD backend"
        rbd_store_pool = images
        rbd_store_user = openstack
        [ceph-1]
        rbd_store_ceph_conf = /etc/ceph/ceph-1.conf
        store_description = "RBD backend 1"
        rbd_store_pool = images
        rbd_store_user = openstack
        [swift-0]
        swift_store_create_container_on_put = True
        swift_store_auth_version = 3
        swift_store_auth_address = {{ .KeystoneInternalURL }}
        swift_store_key = {{ .ServicePassword }}
        swift_store_user = service:glance
        swift_store_endpoint_type = internalURL
      databaseInstance: openstack
      databaseAccount: glance
      glanceAPIs:
        default:
          debug:
            service: false
          preserveJobs: false
          replicas: 1
      secret: osp-secret
      storageClass: ""
      storageRequest: 1G
  extraMounts:
    - name: v1
      region: r1
      extraVol:
        - propagation:
          - GlanceAPI
          extraVolType: Ceph
          volumes:
          - name: ceph
            projected:
              sources:
              - secret:
                  name: ceph-client-conf-0
              - secret:
                  name: ceph-client-conf-1
          mounts:
          - name: ceph
            mountPath: "/etc/ceph"
            readOnly: true
