# Sample of a Glance CR where quotas are customized
apiVersion: glance.openstack.org/v1beta1
kind: Glance
metadata:
  name: glance
spec:
  serviceUser: glance
  databaseInstance: openstack
  databaseAccount: glance
  keystoneEndpoint: default
  glanceAPIs:
    default:
      debug:
        service: false
      preserveJobs: false
      replicas: 1
      type: single
  secret: osp-secret
  storageClass: ""
  storageRequest: 1G
  quotas:
    imageSizeTotal: 1000
    imageStageTotal: 1000
    imageCountUpload: 100
    imageCountTotal: 100
