apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    features.operators.openshift.io/disconnected: "true"
    operators.openshift.io/infrastructure-features: '["disconnected"]'
    operators.operatorframework.io/operator-type: non-standalone
  name: glance-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: GlanceAPI is the Schema for the glanceapis API
      displayName: Glance API
      kind: GlanceAPI
      name: glanceapis.glance.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: tls
      version: v1beta1
    - description: Glance is the Schema for the glances API
      displayName: Glance
      kind: Glance
      name: glances.glance.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: glanceAPIs.tls
      version: v1beta1
  description: Glance Operator
  displayName: Glance Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - OpenStack
  - Image
  - Glance
  links:
  - name: Glance Operator
    url: https://github.com/openstack-k8s-operators/glance-operator
  maturity: alpha
  provider:
    name: Red Hat
    url: https://redhat.com
  version: 0.0.0
