apiVersion: glance.openstack.org/v1beta1
kind: GlanceAPI
metadata:
  name: default
  annotation:
    keystoneEndpoint: "true"
spec:
  serviceUser: glance
  serviceAccount: glance
  customServiceConfig: |
    [DEFAULT]
    debug = true
    enabled_backends=foo:bar,foo1:bar1
    [foo]
    here-foo-config
    [foo1]
    here-foo1-config
  databaseAccount: glance
  databaseHostname: glance
  debug:
    dbSync: false
    service: false
  preserveJobs: false
  replicas: 1
  storageRequest: 10G
  secret: glance-secret
  #tls:
  #  api:
  #    # secret holding tls.crt and tls.key for the APIs internal k8s service
  #    internal:
  #      secretName: cert-internal-svc
  #    # secret holding tls.crt and tls.key for the APIs public k8s service
  #    public:
  #      secretName: cert-public-svc
  #  # secret holding the tls-ca-bundle.pem to be used as a deploymend env CA bundle
  #  caBundleSecretName: combined-ca-bundle
