apiVersion: glance.openstack.org/v1beta1
kind: Glance
metadata:
  name: glance
spec:
  serviceUser: glance
  customServiceConfig: |
    [oslo_policy]
    policy_file=/etc/glance/policy.d/policy.yaml
    enforce_scope=true
    enforce_new_defaults=true
  databaseInstance: openstack
  databaseAccount: glance
  glanceAPI:
    preserveJobs: false
    replicas: 1
  secret: osp-secret
  storageClass: ""
  storageRequest: 10G
  extraMounts:
    - name: v1
      region: r1
      extraVol:
        - propagation:
            - GlanceAPI
          extraVolType: Policy
          volumes:
            - name: glance-policy
              configMap:
                name: glance-policy
          mounts:
            - name: glance-policy
              mountPath: /etc/glance/policy.d/
              readOnly: true
