apiVersion: glance.openstack.org/v1beta1
kind: Glance
metadata:
  name: glance
spec:
  serviceUser: glance
  customServiceConfig: |
    [DEFAULT]
    debug = true
    enabled_backends=foo:bar
  databaseInstance: openstack
  databaseAccount: glance
  secret: osp-secret
  storageClass: local-storage
  storageRequest: 10G
